/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProyectoFinal;

import ProyectoFinal.View.LoginView;

public class App {
    

    public static void main(String[] args) {
        LoginView loginView = new LoginView();
        loginView.setVisible(true);

    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
